### ISSUE TITLE
Wrong output in version comparisation

### ISSUE THREAD

**Issue by teunis90** [valorin/debver#1]
Hi Stephen,

I know you marked this package as abandoned, but still like to file this issue (You never know who is looking into this in the future) 

Tragically the '2.7.8.dfsg-2+squeeze8' updates is seen as the most recent one.

2.7.8.dfsg-2+squeeze8 <-- Marked as newer
2.7.8.dfsg-2+squeeze10

I played a bit with the version to find out where the real issue is:

2.7.8.dfsg-2+squeeze2 
2.7.8.dfsg-2+squeeze30 <-- Marked as newer

2.7.8.dfsg-2+squeeze3 
2.7.8.dfsg-2+squeeze30 <-- Marked as newer

Next one is interesting:

2.7.8.dfsg-2+squeeze4 <-- Marked as newer
2.7.8.dfsg-2+squeeze30

So I think when there starts a digit part is should compare the complete number instead of per character.

I made a fork of your code if I have time I try to solve this issue. But if you have a clue where to start please leave a comment.

Best,

Teun

**Comment by valorin** [comment]
No worries :-)

At first glance, I'd say that it's comparing `squeeze8` and `squeeze10` as strings, which means the first one is going to come out as higher. It would need to explode the chars from the digits and compare them separately - or do some injected zero padding...

I assume you're not using the `compareWithDpkg()` function?

**Comment by teunis90** [comment]
No I do not use the `compareWithDpkg()` function, that would be to slow for what I try to accomplish.

I created a pull request, do you mind to take a look?

**Comment by valorin** [comment]
PR merged :-)
